# Generated by Django 5.0.6 on 2024-06-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.IntegerField(default=10000000, primary_key=True, serialize=False)),
            ],
        ),
    ]
