# Generated by Django 5.0.6 on 2024-06-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='name',
            field=models.CharField(default='用户<django.db.models.fields.IntegerField>', max_length=100),
        ),
    ]
