# Generated by Django 5.0.6 on 2024-07-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='time_buy',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='time_cancel',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='reason',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='way',
            field=models.IntegerField(null=True),
        ),
    ]
