# Generated by Django 5.0.6 on 2024-07-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_orderinfo_time_buy_orderinfo_time_cancel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='price',
            field=models.BigIntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='user_phone',
            field=models.IntegerField(null=True),
        ),
    ]
