# Generated by Django 5.0.6 on 2024-06-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_user_info_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
