# Generated by Django 5.0.6 on 2024-07-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_orderinfo_price_alter_orderinfo_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='price',
            field=models.IntegerField(max_length=100),
        ),
    ]
