# Generated by Django 5.0.6 on 2024-06-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_user_info_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_info',
            name='password',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_info',
            name='username',
            field=models.CharField(default=111, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_info',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
