# Generated by Django 5.0.6 on 2024-07-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_orderinfo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
