# Generated by Django 5.0.6 on 2024-06-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_user_info_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
