# Generated by Django 5.0.6 on 2024-07-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_orderinfo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='good_image',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
