# Generated by Django 5.0.6 on 2024-06-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_user_info_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='realid',
            field=models.IntegerField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_info',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
