# Generated by Django 5.0.6 on 2024-07-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_orderinfo_good_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='time_cancel',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
