# Generated by Django 5.0.6 on 2024-07-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_alter_orderinfo_time_cancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='time_cancel',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
