# Generated by Django 5.0.6 on 2024-06-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_user_info_realid_alter_user_info_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
