# Generated by Django 5.0.6 on 2024-06-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_alter_user_info_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='realid',
        ),
        migrations.AlterField(
            model_name='user_info',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
