# Generated by Django 5.0.6 on 2024-07-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_alter_orderinfo_time_cancel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='time_cancel',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='time_apply',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='time_refund',
            field=models.DateTimeField(null=True),
        ),
    ]
