# Generated by Django 5.0.6 on 2024-07-05 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_alter_user_info_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='goods_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='/static/img/good_default_image.png', upload_to='images/')),
                ('type', models.IntegerField()),
                ('price', models.IntegerField()),
                ('topic', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=200)),
                ('inventory', models.IntegerField()),
            ],
            options={
                'db_table': 'goods_info',
            },
        ),
        migrations.CreateModel(
            name='order_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_address', models.CharField(max_length=100)),
                ('user_phone', models.IntegerField()),
                ('good_name', models.CharField(max_length=100)),
                ('good_image', models.ImageField(upload_to='images/')),
                ('good_price', models.IntegerField()),
                ('count', models.IntegerField()),
                ('state', models.IntegerField()),
                ('price', models.IntegerField()),
                ('way', models.IntegerField()),
                ('reason', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'order_info',
            },
        ),
        migrations.AddField(
            model_name='user_info',
            name='identity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_info',
            name='image',
            field=models.ImageField(default='/static/img/default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user_info',
            name='phonenum',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='sex',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='user_info',
            table='user_info',
        ),
        migrations.CreateModel(
            name='address_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.user_info')),
            ],
            options={
                'db_table': 'address_info',
            },
        ),
        migrations.CreateModel(
            name='cart_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.user_info')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.goods_info')),
            ],
            options={
                'db_table': 'cart_info',
            },
        ),
        migrations.CreateModel(
            name='store_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phonenum', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.user_info')),
            ],
            options={
                'db_table': 'store_info',
            },
        ),
        migrations.AddField(
            model_name='goods_info',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.store_info'),
        ),
    ]
