# Generated by Django 5.0.6 on 2024-07-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_goods_info_order_info_user_info_identity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods_info',
            old_name='store_id',
            new_name='store',
        ),
    ]
