# Generated by Django 5.0.6 on 2024-07-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_rename_store_id_goods_info_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='image',
            field=models.TextField(default='default.jpg'),
        ),
    ]
