# Generated by Django 5.0.6 on 2024-07-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_alter_user_info_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_info',
            name='image',
            field=models.TextField(default='default.jpg'),
        ),
    ]
